added new source
sdtrdev/source-pocket pull request #92
Opened 2021-02-24 21:19 UTC by suleymanfatih

## What type of PR is this? (check all applicable)

- [x] Added new link to category
- [ ] New category added
- [ ] Fixed broken link
- [ ] Typo fix
- [ ] Readme update
- [ ] Optimization
- [ ] Documentation update
- [ ] Frontend update

## Description
vim ile ilgili yeni kaynaklar eklendi
## [optional] Related Issues & Documents

## [optional] QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## [optional] Anything Else?

2021-02-24 21:49 UTC, suleymanfatih commented
bi yeri yanlış işaretlemişim onu editledm

2021-02-25 10:15 UTC, damla requested changes

2021-02-25 10:15 UTC, damla commented on docs/development-tools/vim.md
>  ## Beginner
```suggestion
## Beginner

```

2021-02-25 10:15 UTC, damla commented on docs/development-tools/vim.md
> +* [Introduction To Vim Customization](https://www.linode.com/docs/guides/introduction-to-vim-customization/ "Introduction To Vim Customization")
```suggestion
- [Cheat Sheet Image](https://i.imgur.com/YLInLlY.png "Cheat Sheet")
- [The Ultimate Vim configuration](https://github.com/amix/vimrc "The Ultimate Vim configuration")
- [Vim Cheat Sheet](https://vim.rtorr.com/ "Vim Cheat Sheet")

## Intermediate

- [Vim Sence](https://github.com/hugolgst/vimsence "Vim Sence")
- [Introduction To Vim Customization](https://www.linode.com/docs/guides/introduction-to-vim-customization/ "Introduction To Vim Customization")
```

2021-02-25 10:26 UTC, damla approved these changes

2021-02-25 10:26 UTC, merged

2021-02-25 10:27 UTC, damla commented
Selam @suleymanfatih,
Bulunduğun branchi eşitlememenden kaynaklı conflictler oluştu. Ben çözümlemeyi hallettim yine kontrol edersin fakat sonraki PR'larında burada yaptığım değişikliklere ve her zaman dalını eşitlemeye dikkat edebilirsen sevinirim. 🙃